- name: debug demo
  hosts: all
  vars:
    URL: cloudblitz.in

  tasks:
    - debug:
        msg: "Hello world, {{ URL }}"
    vars:
      URL: local.cloudblitz.in
    -  debug:
         msg: "Hello world, {{ URL }}"

         
         









# Global variables